// Generated by python/quant/run.py; source: quant_config.json
#pragma once
#define LENET_DATA_W 12
#define LENET_DATA_I 7
#define LENET_WEIGHT_W 12
#define LENET_WEIGHT_I 1
#define LENET_ACC_W 32
#define LENET_ACC_I 16
